name: Apigee Platform CI

on:
  push:
    branches:
      - feature-adarsha
      - release

  workflow_dispatch:

jobs:
  apigee-ci:
    uses: ForgeCrux/pipeline-template/.github/workflows/apigee-v2.yaml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit      
    with:
      apigee_org: gen-ai-poc-onboarding
      apigee_env: dev
      deploy_proxy: forgenotifier-event-driven-notification-alerting-service
      resourcetype: apis
      branch_name: ${{ github.ref_name }}
